import { useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Play, Pause, StopCircle, Award, Archive } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";

interface WorkshopSettingsTabProps {
  workshopId: string;
  workshop: any;
  onUpdate: () => void;
}

const WorkshopSettingsTab = ({ workshopId, workshop, onUpdate }: WorkshopSettingsTabProps) => {
  const { toast } = useToast();
  const [isLoading, setIsLoading] = useState(false);

  const handleStartWorkshop = async () => {
    setIsLoading(true);
    // Update all tasks to be visible/accessible
    const { error } = await supabase
      .from('workshops')
      .update({ updated_at: new Date().toISOString() })
      .eq('id', workshopId);

    if (error) {
      toast({ title: "Error starting workshop", variant: "destructive" });
    } else {
      toast({ title: "Workshop started! All systems active." });
      onUpdate();
    }
    setIsLoading(false);
  };

  const handleEndWorkshop = async () => {
    setIsLoading(true);
    // Deactivate all tasks
    await supabase
      .from('workshop_tasks')
      .update({ is_active: false })
      .eq('workshop_id', workshopId);

    toast({ title: "Workshop ended. All tasks locked." });
    setIsLoading(false);
  };

  const handleGenerateCertificates = async () => {
    setIsLoading(true);
    
    // Get all participants
    const { data: participants } = await supabase
      .from('user_workshops')
      .select('user_id')
      .eq('workshop_id', workshopId);

    if (participants) {
      const certificates = participants.map(p => ({
        user_id: p.user_id,
        title: `${workshop.title} - Certificate of Completion`,
        download_url: null, // Would be generated by a background process
      }));

      const { error } = await supabase
        .from('certificates')
        .insert(certificates);

      if (error) {
        toast({ title: "Error generating certificates", variant: "destructive" });
      } else {
        toast({ title: `${participants.length} certificates queued for generation` });
      }
    }
    
    setIsLoading(false);
  };

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-2xl font-bold">Workshop Control Panel</h2>
        <p className="text-muted-foreground">Manage workshop state and global settings</p>
      </div>

      {/* Workshop Controls */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Play className="h-5 w-5 text-green-600" />
              Start Workshop
            </CardTitle>
            <CardDescription>Enable all features and allow task submissions</CardDescription>
          </CardHeader>
          <CardContent>
            <AlertDialog>
              <AlertDialogTrigger asChild>
                <Button className="w-full" disabled={isLoading}>
                  Start Workshop
                </Button>
              </AlertDialogTrigger>
              <AlertDialogContent>
                <AlertDialogHeader>
                  <AlertDialogTitle>Start Workshop?</AlertDialogTitle>
                  <AlertDialogDescription>
                    This will activate the workshop for all participants. Tasks can be controlled individually.
                  </AlertDialogDescription>
                </AlertDialogHeader>
                <AlertDialogFooter>
                  <AlertDialogCancel>Cancel</AlertDialogCancel>
                  <AlertDialogAction onClick={handleStartWorkshop}>Start</AlertDialogAction>
                </AlertDialogFooter>
              </AlertDialogContent>
            </AlertDialog>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <StopCircle className="h-5 w-5 text-red-600" />
              End Workshop
            </CardTitle>
            <CardDescription>Lock all tasks and finalize leaderboard</CardDescription>
          </CardHeader>
          <CardContent>
            <AlertDialog>
              <AlertDialogTrigger asChild>
                <Button variant="destructive" className="w-full" disabled={isLoading}>
                  End Workshop
                </Button>
              </AlertDialogTrigger>
              <AlertDialogContent>
                <AlertDialogHeader>
                  <AlertDialogTitle>End Workshop?</AlertDialogTitle>
                  <AlertDialogDescription>
                    This will lock all tasks and prevent further submissions. This action is permanent.
                  </AlertDialogDescription>
                </AlertDialogHeader>
                <AlertDialogFooter>
                  <AlertDialogCancel>Cancel</AlertDialogCancel>
                  <AlertDialogAction onClick={handleEndWorkshop}>End Workshop</AlertDialogAction>
                </AlertDialogFooter>
              </AlertDialogContent>
            </AlertDialog>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Award className="h-5 w-5 text-yellow-600" />
              Generate Certificates
            </CardTitle>
            <CardDescription>Create certificates for all participants</CardDescription>
          </CardHeader>
          <CardContent>
            <Button onClick={handleGenerateCertificates} className="w-full" disabled={isLoading}>
              Generate Certificates
            </Button>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Archive className="h-5 w-5" />
              Archive Workshop
            </CardTitle>
            <CardDescription>Move to read-only archived state</CardDescription>
          </CardHeader>
          <CardContent>
            <Button variant="outline" className="w-full" disabled>
              Archive (Coming Soon)
            </Button>
          </CardContent>
        </Card>
      </div>

      {/* Workshop Info */}
      <Card>
        <CardHeader>
          <CardTitle>Workshop Information</CardTitle>
        </CardHeader>
        <CardContent className="space-y-2">
          <div className="flex justify-between">
            <span className="text-muted-foreground">Workshop ID:</span>
            <code className="text-sm">{workshopId}</code>
          </div>
          <div className="flex justify-between">
            <span className="text-muted-foreground">Created:</span>
            <span>{new Date(workshop.created_at).toLocaleDateString()}</span>
          </div>
          <div className="flex justify-between">
            <span className="text-muted-foreground">Last Updated:</span>
            <span>{new Date(workshop.updated_at).toLocaleDateString()}</span>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default WorkshopSettingsTab;
